import Logout from "@/components/auth/LogOut";
import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import Providers from "@/components/auth/Providers";
import Navbar from "@/components/layout/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className}`}>
        <Providers>
          <div className="max-w-7xl mx-auto md:container ">
            <Navbar />
            {/* <div className="relative flex-1 overflow-hidden"> */}
            {/* usually classname has container for the side margins. and pt-20 */}
            <div className="min-h-screen">{children}</div>
            {/* </div> */}
          </div>
        </Providers>
      </body>
    </html>
  );
}
